name: Bella Tests
on: push
jobs:
  build:
    strategy:
      matrix:
        include:
          - elixir: 1.13.0
            otp: 24.2
            lint: lint
          - elixir: 1.12.0
            otp: 24.0

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          mix deps.get
          mix deps.get --only test
      - name: Compile
        run: |
          mix compile --warnings-as-errors --force
      - name: Lint
        run: mix credo --strict
        if: ${{ matrix.lint }}
      - name: Run Tests
        run: mix test
